version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: mysqlcontainer
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: qr-sopra
    volumes:
      - db_data:/var/lib/mysql  # Persist database data

volumes:
  db_data:
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
